### PR TITLE
fix(StyleManager): use palette instead of stylesheet for tooltips

### LINKED ISSUE #604: Message logger font automatically resets.
**Describe the bug**
After applying the message logger font, it stays applied only till cpeditor is open. When closing and reopening cpeditor, the message logger font shows an unknown font and unknown font size. Basically it resets my applied font to some other font on every launch. However in the settings it shows the correct name of the font which I had applied. And because of that I've to set the message logger font everytime.

**To Reproduce**
Set the UI style as auto/light/dark fusion and the message logger font to some distinguishable font. Then relaunch cpeditor and run a sample program.

**Screenshots**
After setting the message logger font-

Screenshot (73)

After closing and relaunching cpeditor-

Screenshot (74)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.64/6.5 (Tried on both)

**Additional context**
None

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Now the color of the tooltips are controlled by the palette, and the stylesheet is not changed.

## Related Issue

This fixes #604 and reverts #606.

## Motivation and Context

1. #604 is caused by unexpected behavior when setting the stylesheet. Instead of changing the order of applying settings, getting rid of the stylesheet has no side effects like #610.
2. I think the new palettes actually seem better than the old stylesheets.

## How Has This Been Tested?

On Arch Linux KDE and Windows, with Dark Fusion and Light Fusion and message logger font changed.

## Screenshots (if appropriate)

image

image

## Type of changes

- [x] Bug fix (changes which fix an issue)
- [x] Revert (revert previous changes)

## Checklist

- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ouuan** [comment]
In fact, I've been wondering about `darkPalette.setColor(QPalette::ToolTipBase, Qt::white);` and `lightPalette.setColor(QPalette::ToolTipBase, Qt::black);` for a long time.

File: src/appwindow.cpp [hunk 1]
```diff
@@ -1010,6 +1010,12 @@ void AppWindow::onSettingsApplied(const QString &pagePath)
 {
     LOG_INFO("Apply settings for " << INFO_OF(pagePath));
 
+    for (int i = 0; i < ui->tabWidget->count(); ++i)
```
Comment (coder3101) [inline src/appwindow.cpp:1013]: Why do you want to apply the settings to each tab then to whole application?

Comment (ouuan) [reply src/appwindow.cpp:1013]: Because there's no need to do the reverse, which could lead to unforeseen bugs.

Comment (coder3101) [reply src/appwindow.cpp:1013]: I changed the order because of some issues, I'll check if it happens after your palette based stylings and let you know.

Comment (coder3101) [reply src/appwindow.cpp:1013]: I checked its fine!

**Review by coder3101 — APPROVED** [review]
LGTM
